### ISSUE TITLE
Console error when using ?_escaped_fragment_= 

### ISSUE THREAD

**Issue by BradRyan** [ongoworks/spiderable#1]
Not sure if this is a problem or not, but when switching to this package from spiderable I got the following  error in my browser console: 
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('http://localhost:26424') does not match the recipient window's origin ('http://localhost:3000').window.onload @ channel.html?stripe_xdm_e=http%3A%2F%2Flocalhost%3A26424&stripe_xdm_c=default112422&stripe_xdm_p=1:25

I'm a newbie when it comes to spiderable and phantomjs... Is this an error I should be worried about?  I don't get the error when omitting the escaped fragment.  The page renders, but I'm hoping it doesn't lead to issues with page crawling.

**Comment by BradRyan** [comment]
Actually when hosting on the server I get the following error on the browser window itself when including the escaped fragment:

ReferenceError: Can't find variable: Stripe

  http://localhost:8080/565a9e95138619c4ffb527bd07b1d6785d06516c.js:326
  http://localhost:8080/565a9e95138619c4ffb527bd07b1d6785d06516c.js:3
  http://localhost:8080/565a9e95138619c4ffb527bd07b1d6785d06516c.js:3

**Comment by aaronjudd** [comment]
the stripe error should be unrelated.  Perhaps that's a different issue? In any case, doesn't sound like it's working (or configured) properly  - you shouldn't see any errors.  this version of spiderable was made specifically to deal with docker (or a proxy) where spiderable needs to work behind a defined port. you might try passing --port xxxx to the meteor statement.  Unless you are having specific problems with proxies, docker,etc I'd probably suggest not using this package. regular meteor:spiderable should work locally in most all cases.

**Comment by BradRyan** [comment]
Got it.  I was having errors occur on Modulus, so I gave it a try, but it seems to be resolved with an alternative phantomJS package.  Not sure why the stripe error.  It went away when switching back to the regular spiderable package.
