### ISSUE TITLE
Conflicted with Iron:router?

### ISSUE THREAD

**Issue by kafechew** [ongoworks/spiderable#2]
After I added the spiderable package, seems like it conflicted with the iron:router package :(
How can I fix this? 

Attached is the mup logs:

> at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
>     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
>     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
>     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
>     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
>     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
>     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
>     at Object.router (packages/iron:router/lib/router.js:15:1)
>     at next (/opt/geosenti/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>     at packages/ongoworks:spiderable/spiderable_server.js:131:1
> [169.54.246.212] spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
> stderr: 
> [169.54.246.212] Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
>     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
>     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
>     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
>     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
>     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
>     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
>     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
>     at Object.router (packages/iron:router/lib/router.js:15:1)
>     at next (/opt/geosenti/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>     at packages/ongoworks:spiderable/spiderable_server.js:131:1
> [169.54.246.212] spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
> stderr: 
> Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
>     at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/dynamics_nodejs.js:9:1)
>     at [object Object]._.extend.get (packages/meteor/dynamics_nodejs.js:21:1)
>     at [object Object].RouteController.lookupOption (packages/iron:router/lib/route_controller.js:66:1)
> [169.54.246.212]     at new Controller.extend.constructor (packages/iron:router/lib/route_controller.js:26:1)
>     at [object Object].ctor (packages/iron:core/lib/iron_core.js:88:1)
>     at Function.Router.createController (packages/iron:router/lib/router.js:201:1)
>     at Function.Router.dispatch (packages/iron:router/lib/router_server.js:39:1)
>     at Object.router (packages/iron:router/lib/router.js:15:1)
>     at next (/opt/geosenti/app/programs/server/npm/webapp/node_modules/connect/lib/proto.js:190:15)
>     at packages/ongoworks:spiderable/spiderable_server.js:131:1

Thanks!

**Comment by aaronjudd** [comment]
I'm not sure, I actually use this with iron:router without issue. Perhaps make sure the spiderable package is loaded before iron:router?

**Comment by strikeout** [comment]
Something is BREAKING your spidarable execution. See http://www.meteorpedia.com/read/spiderable and use the script on the page to have a local spiderable render and debug your meteor app.
I used this to find an _external_ jquery addon lib crashing my stack by using an unsupported method on the window/document and giving me the same errors you mentioned - nasty

**Comment by epeng5** [comment]
I may have run into the same problem on Modulus. Any updates here?

Here's the logs:

```
spiderable: phantomjs failed: Error: Command failed: 
at ChildProcess.exithandler (child_process.js:658:15)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Process.ChildProcess.handle.onexit (childprocess.js:833:5) 
stderr:

Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
at Object.Meteor._nodeCodeMustBeInFiber (packages/meteor/packages/meteor.js:966:1)
at [object Object]._.extend.get (packages/meteor/packages/meteor.js:978:1)
at [object Object].RouteController.lookupOption (packages/iron_router/packages/iron_router.js:122:1)
at new Controller.extend.constructor (packages/iron_router/packages/iron_router.js:82:1)
at [object Object].ctor (packages/iron_core/packages/iron_core.js:132:1)
at Function.Router.createController (packages/iron_router/packages/iron_router.js:789:1)
at Function.Router.dispatch (packages/iron_router/packages/iron_router.js:1314:1)
at Object.router (packages/iron_router/packages/iron_router.js:603:1)
at next (/mnt/app/node_modules/connect/lib/proto.js:190:15)
at packages/ongoworks_spiderable/packages/ongoworks_spiderable.js:159:1
at ChildProcess.exithandler (child_process.js:662:7)
at ChildProcess.emit (events.js:98:17)
at maybeClose (child_process.js:766:16)
at Process.ChildProcess.handle.onexit (childprocess.js:833:5)
```

**Comment by epeng5** [comment]
Turns out this was an issue with a separate package (https://atmospherejs.com/okgrow/router-autoscroll) that conflicted with iron router. Once I removed it, things worked again.

**Comment by aaronjudd** [comment]
Thanks for the update. 

We're not doing anything in this package that should conflict, in any way that the default `spiderable` package would not also do.  Also, this package was really meant as a temporary solution until Meteor started to pay more attention to the fact that everyone needs SEO.  I'm not sure that's going to happen,  but until a better solution comes along...  this package will just be in maintenance mode.

**Comment by Pushplaybang** [comment]
Getting exactly the same issue,  Its a pity that this is only in maintenance mode... its the only spiderable implementation thats working for me at the moment.  I'm getting results, but a similar error to the above as well.

**Comment by aaronjudd** [comment]
@Pushplaybang is it `router-autoscroll` or some other package that's causing the issue for you?  (iron-router has always worked with ongoworks:spiderable for us). I'm willing to take a look now if I have a sure way to replicate the error.

**Comment by Pushplaybang** [comment]
@aaronjudd  - not using autoscroll, going to dig back into this tomorrow, I was tring to use another iron-router plugin lookback SEO.  But after ditching I've some success, still one or two errors to handle though.

I will get back on this tomorrow, working on a production app with a deadline looming so any help would be amazing.
