### ISSUE TITLE
error with meteor 1.4

### ISSUE THREAD

**Issue by berkaytheunicorn** [ongoworks/spiderable#4]
hey Im deploying meteor 1.4 with `kadirahq/mup` with `abernix/meteord:base`docker image

and getting this

```
spiderable: phantomjs failed: { [Error: Command failed: /bin/bash -c exec phantomjs --load-images=no --ignore-ssl-errors=yes /tmp/meteor_3044071958

 killed: true,
  code: null,
  signal: 'SIGTERM',
  cmd: '/bin/bash -c exec phantomjs --load-images=no --ignore-ssl-errors=yes /tmp/meteor_3044071958' } 
stderr: 
```

installing phantomjs manually with apt-get wont fixed the issue btw.

**Comment by berkaytheunicorn** [comment]
it is also happens on local too.

**Comment by aaronjudd** [comment]
I just tested with Meteor 1.4.0.1, on OSX with phantomjs v2.1.1 (installed via brew) and was unable to reproduce locally.

**Comment by berkaytheunicorn** [comment]
oh, sorry. I found that issue is actually related to Meteor publish functions. On some of them I didnt return empty array or just didnt call this.ready(). so when I fixed all my publish code. It actually fixed.
