### ISSUE TITLE
Is this package good with meteor 1.3?

### ISSUE THREAD

**Issue by kenshinman** [ongoworks/spiderable#5]
When i add this package, i got this error

`spiderable: phantomjs failed at http://localhost:3000/: { [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }`

How can I get this to work?
Thanks

**Comment by aaronjudd** [comment]
Tested with Meteor 1.4+ still working..  `ENOENT` means probably that no `/tmp` dir is available?  Perhaps try `meteor:spiderable` instead?
